CapaPresentacionAdmin/Controllers/MantenedorController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Marca()
        {
            return View();
        }
        public ActionResult Producto()
        {
            return View();
        }

        //***Categoria***\\
        #region
        [HttpGet]
        public JsonResult ListarCategorias()
        {
            List<Categoria> olist = new List<Categoria>();
            olist = new CN_Categoria().Listar();
            return Json(new {data = olist}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarCategoria(Categoria cat)
        {
            object resultado;
            string mensaje = string.Empty;

            if (cat.IdCategoria == 0)
            {
                resultado = new CN_Categoria().Registrar(cat, out mensaje);

            }
            else
            {
                resultado = new CN_Categoria().Editar(cat, out mensaje);
            }
            return Json(new {resultado = resultado, mensaje = mensaje}, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool rpta = false;
            string mensaje = string.Empty;

            rpta = new CN_Categoria().Eliminar(id, out mensaje);

            return Json(new {result = rpta, mensaje = mensaje}, JsonRequestBehavior.AllowGet);
        }
        #endregion


        //***MARCA***\\
        #region
        [HttpGet]
        public JsonResult ListarMarca()
        {
            List<Marca> oLista = new List<Marca>();
            oLista = new CN_Marca().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarMarca(Marca obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if(obj.IdMarca == 0)
            {
                resultado = new CN_Marca().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_Marca().Editar(obj, out mensaje);
            }
            return Json(new {resultado = resultado, mensaje = mensaje}, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);  

            return Json(new {resultado = respuesta, mensaje = mensaje}, JsonRequestBehavior.AllowGet);  
        }

        #endregion


        //***PRODUCTO***\\
        #region

        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> oProd = new List<Producto>();
            oProd = new CN_Producto().Listar();
            return Json(new { data = oProd }, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public JsonResult RegistrarProducto(string obj, HttpPostedFileBase fileImg)
        {
            
            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool save_image_success = true;

            Producto oProduct = new Producto();
            oProduct = JsonConvert.DeserializeObject<Producto>(obj);

            decimal precio;

            if(decimal.TryParse(oProduct.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-PE"), out precio))
            {
                oProduct.Precio = precio;
            }
            else
            {
                return Json(new { operacionExitosa = false, mensaje = "El formato del precio debe ser ##.##"}, JsonRequestBehavior.AllowGet);
            }

            if (oProduct.IdProducto == 0)
            {
                int idProductoGen = new CN_Producto().Registrar(oProduct, out mensaje);

                if (idProductoGen != 0)
                {
                    oProduct.IdProducto = idProductoGen;
                }
                else
                {
                    operacion_exitosa = false;
                }

            }
            else
            {
                operacion_exitosa = new CN_Producto().Editar(oProduct, out mensaje);
            }

            if (operacion_exitosa)
            {
                if(fileImg != null)
                {

                    string rute_save = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(fileImg.FileName);
                    string name_img = string.Concat(oProduct.IdProducto.ToString(), extension);

                    try
                    {
                        fileImg.SaveAs(Path.Combine(rute_save, name_img));
                    }
                    catch (Exception ex)
                    {
                        string msg = ex.Message;
                        save_image_success = false;

                    }

                    if (save_image_success)
                    {
                        oProduct.RutaImagen = rute_save;
                        oProduct.NombreImagen = name_img;
                        bool rpta = new CN_Producto().SaveDataImg(oProduct, out mensaje);
                    }
                    else
                    {
                        mensaje = "Producto registrado, pero hubo problemas al gurdar la imagen";
                    }
                }
            }

            return Json(new {operacionExitosa = operacion_exitosa, idGenerado = oProduct.IdProducto, mensaje = mensaje}, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult ImgProduct(int id)
        {

            bool conversion;
            Producto oProd = new CN_Producto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();

            string textBase64 = CN_Recursos.ConvertBase64(Path.Combine(oProd.RutaImagen,oProd.NombreImagen), out conversion);

            return Json(new
            {
                conversion = conversion,
                textBase64 = textBase64,
                extension = Path.GetExtension(oProd.NombreImagen)
            },
                JsonRequestBehavior.AllowGet
            );

        }

        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool rpta = false;
            string mensaje = string.Empty;

            rpta = new CN_Producto().Eliminar(id, out mensaje);

            return Json(new { resultado = rpta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion


    }
}

CapaPresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mr. ROBOT</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Mr. ROBOT</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">UserMail</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("CloseSession","Acceso")">Cerrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Usuarios
                        </a>


                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Categoria","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" href="@Url.Action("Marca","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" href="@Url.Action("Producto","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Current User
                    </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; My ecommerce 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


   
    @*<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de la tienda", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
        <li>@Html.ActionLink("Testing page", "PageTest", "Home")</li>*@


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>